
localelect,next,totring,pcall,getgenv,etmetatable,mathfloor,mathab,mathco,mathin,mathrad,wait=elect,next,totring,pcall,getgenv,etmetatable,math.floor,math.ab,math.co,math.in,math.rad,tak.wait
localWorldToViewportPoint,Vector2new,Vector3new,Vector3zero,CFramenew,Drawingnew,Color3fromRGB=nil,Vector2.new,Vector3.new,Vector3.zero,CFrame.new,Drawing.new,Color3.fromRGB
ifnotgetgenv().natxyzEPorgetgenv().natxyzEP.WallHackthenreturnend
localRunervice=game:Getervice("Runervice")
localUerInputervice=game:Getervice("UerInputervice")
localPlayer=game:Getervice("Player")
localLocalPlayer=Player.LocalPlayer
localCamera=workpace.CurrentCamera
localerviceConnection={}
getgenv().natxyzESP.WallHack={
etting={
Enabled=fale,
TeamCheck=fale,
AliveCheck=true
},
Viual={
Chametting={
Enabled=fale,
Color=Color3fromRGB(255,255,255),
Tranparency=0.2,
Thickne=0,
Filled=true,
EntireBody=fale--ForR15,keepfaletopreventlag
},
EPetting={
Enabled=true,
TextColor=Color3fromRGB(255,255,255),
Textize=14,
Outline=true,
OutlineColor=Color3fromRGB(0,0,0),
TextTranparency=0.7,
TextFont=Drawing.Font.UI,--UI,ytem,Plex,Monopace
Offet=20,
DiplayDitance=true,
DiplayHealth=true,
DiplayName=true
},
Traceretting={
Enabled=true,
Type=1,--1-Bottom;2-Center;3-Moue
Tranparency=0.7,
Thickne=1,
Color=Color3fromRGB(255,255,255)
},
Boxetting={
Enabled=true,
Type=1;--1-3D;2-2D
Color=Color3fromRGB(255,255,255),
Tranparency=0.7,
Thickne=1,
Filled=fale,--For2D
Increae=1--For3D
},
HeadDotetting={
Enabled=true,
Color=Color3fromRGB(255,255,255),
Tranparency=0.5,
Thickne=1,
Filled=fale,
ide=30
},
HealthBaretting={
Enabled=fale,
Tranparency=0.8,
ize=2,
Offet=10,
OutlineColor=Color3fromRGB(0,0,0),
Blue=50,
Type=3
}
},
Crohair={
etting={
Enabled=fale,
Type=1,
ize=12,
Thickne=1,
Color=Color3fromRGB(0,255,0),
Tranparency=1,
Gapize=5,
Rotation=0,
CenterDot=fale,
CenterDotColor=Color3fromRGB(0,255,0),
CenterDotize=1,
CenterDotTranparency=1,
CenterDotFilled=true,
CenterDotThickne=1
},
Part={
LeftLine=Drawingnew("Line"),
RightLine=Drawingnew("Line"),
TopLine=Drawingnew("Line"),
BottomLine=Drawingnew("Line"),
CenterDot=Drawingnew("Circle")
}
},
WrappedPlayer={}
}
localEnvironment=getgenv().natxyzEP.WallHack
WorldToViewportPoint=function(...)
returnCamera.WorldToViewportPoint(Camera,...)
end
localfunctionGetPlayerTable(Player)
for_,vinnext,Environment.WrappedPlayerdo
ifv.Name==Player.Namethen
returnv
end
end
end
localfunctionAignRigType(Player)
localPlayerTable=GetPlayerTable(Player)
repeatwait(0)untilPlayer.Character
ifPlayer.Character:FindFirtChild("Toro")andnotPlayer.Character:FindFirtChild("LowerToro")then
PlayerTable.RigType="R6"
eleifPlayer.Character:FindFirtChild("LowerToro")andnotPlayer.Character:FindFirtChild("Toro")then
PlayerTable.RigType="R15"
ele
repeatAignRigType(Player)untilPlayerTable.RigType
end
end
localfunctionInitCheck(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.Connection.UpdateCheck=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")then
ifEnvironment.etting.AliveCheckthen
PlayerTable.Check.Alive=Player.Character:FindFirtChildOfCla("Humanoid").Health>0
ele
PlayerTable.Check.Alive=true
end
ifEnvironment.etting.TeamCheckthen
PlayerTable.Check.Team=Player.TeamColor~=LocalPlayer.TeamColor
ele
PlayerTable.Check.Team=true
end
ele
PlayerTable.Check.Alive=fale
PlayerTable.Check.Team=fale
end
end)
end
localfunctionUpdateCham(Part,Cham)
localCorFrame,Partize=Part.CFrame,Part.ize/2
ifelect(2,WorldToViewportPoint(CorFrame*CFramenew(Partize.X/2,Partize.Y/2,Partize.Z/2).Poition))andEnvironment.Viual.Chametting.Enabledthen
Cham.Quad1.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad1.Color=Environment.Viual.Chametting.Color
Cham.Quad1.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad1.Filled=Environment.Viual.Chametting.Filled
Cham.Quad1.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,Partize.Z).Poition)
localPoTopRight=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,Partize.Z).Poition)
localPoBottomLeft=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,Partize.Z).Poition)
localPoBottomRight=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,Partize.Z).Poition)
Cham.Quad1.PointA=Vector2new(PoTopLeft.X,PoTopLeft.Y)
Cham.Quad1.PointB=Vector2new(PoBottomLeft.X,PoBottomLeft.Y)
Cham.Quad1.PointC=Vector2new(PoBottomRight.X,PoBottomRight.Y)
Cham.Quad1.PointD=Vector2new(PoTopRight.X,PoTopRight.Y)
Cham.Quad2.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad2.Color=Environment.Viual.Chametting.Color
Cham.Quad2.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad2.Filled=Environment.Viual.Chametting.Filled
Cham.Quad2.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft2=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,-Partize.Z).Poition)
localPoTopRight2=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,-Partize.Z).Poition)
localPoBottomLeft2=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,-Partize.Z).Poition)
localPoBottomRight2=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,-Partize.Z).Poition)
Cham.Quad2.PointA=Vector2new(PoTopLeft2.X,PoTopLeft2.Y)
Cham.Quad2.PointB=Vector2new(PoBottomLeft2.X,PoBottomLeft2.Y)
Cham.Quad2.PointC=Vector2new(PoBottomRight2.X,PoBottomRight2.Y)
Cham.Quad2.PointD=Vector2new(PoTopRight2.X,PoTopRight2.Y)
Cham.Quad3.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad3.Color=Environment.Viual.Chametting.Color
Cham.Quad3.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad3.Filled=Environment.Viual.Chametting.Filled
Cham.Quad3.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft3=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,Partize.Z).Poition)
localPoTopRight3=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,Partize.Z).Poition)
localPoBottomLeft3=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,-Partize.Z).Poition)
localPoBottomRight3=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,-Partize.Z).Poition)
Cham.Quad3.PointA=Vector2new(PoTopLeft3.X,PoTopLeft3.Y)
Cham.Quad3.PointB=Vector2new(PoBottomLeft3.X,PoBottomLeft3.Y)
Cham.Quad3.PointC=Vector2new(PoBottomRight3.X,PoBottomRight3.Y)
Cham.Quad3.PointD=Vector2new(PoTopRight3.X,PoTopRight3.Y)
Cham.Quad4.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad4.Color=Environment.Viual.Chametting.Color
Cham.Quad4.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad4.Filled=Environment.Viual.Chametting.Filled
Cham.Quad4.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft4=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,Partize.Z).Poition)
localPoTopRight4=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,Partize.Z).Poition)
localPoBottomLeft4=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,-Partize.Z).Poition)
localPoBottomRight4=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,-Partize.Z).Poition)
Cham.Quad4.PointA=Vector2new(PoTopLeft4.X,PoTopLeft4.Y)
Cham.Quad4.PointB=Vector2new(PoBottomLeft4.X,PoBottomLeft4.Y)
Cham.Quad4.PointC=Vector2new(PoBottomRight4.X,PoBottomRight4.Y)
Cham.Quad4.PointD=Vector2new(PoTopRight4.X,PoTopRight4.Y)
Cham.Quad5.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad5.Color=Environment.Viual.Chametting.Color
Cham.Quad5.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad5.Filled=Environment.Viual.Chametting.Filled
Cham.Quad5.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft5=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,Partize.Z).Poition)
localPoTopRight5=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,Partize.Y,-Partize.Z).Poition)
localPoBottomLeft5=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,Partize.Z).Poition)
localPoBottomRight5=WorldToViewportPoint(CorFrame*CFramenew(Partize.X,-Partize.Y,-Partize.Z).Poition)
Cham.Quad5.PointA=Vector2new(PoTopLeft5.X,PoTopLeft5.Y)
Cham.Quad5.PointB=Vector2new(PoBottomLeft5.X,PoBottomLeft5.Y)
Cham.Quad5.PointC=Vector2new(PoBottomRight5.X,PoBottomRight5.Y)
Cham.Quad5.PointD=Vector2new(PoTopRight5.X,PoTopRight5.Y)
Cham.Quad6.Tranparency=Environment.Viual.Chametting.Tranparency
Cham.Quad6.Color=Environment.Viual.Chametting.Color
Cham.Quad6.Thickne=Environment.Viual.Chametting.Thickne
Cham.Quad6.Filled=Environment.Viual.Chametting.Filled
Cham.Quad6.Viible=Environment.Viual.Chametting.Enabled
localPoTopLeft6=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,Partize.Z).Poition)
localPoTopRight6=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,Partize.Y,-Partize.Z).Poition)
localPoBottomLeft6=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,Partize.Z).Poition)
localPoBottomRight6=WorldToViewportPoint(CorFrame*CFramenew(-Partize.X,-Partize.Y,-Partize.Z).Poition)
Cham.Quad6.PointA=Vector2new(PoTopLeft6.X,PoTopLeft6.Y)
Cham.Quad6.PointB=Vector2new(PoBottomLeft6.X,PoBottomLeft6.Y)
Cham.Quad6.PointC=Vector2new(PoBottomRight6.X,PoBottomRight6.Y)
Cham.Quad6.PointD=Vector2new(PoTopRight6.X,PoTopRight6.Y)
ele
fori=1,6do
Cham["Quad"..totring(i)].Viible=fale
end
end
end
localViual={
AddCham=function(Player)
localPlayerTable=GetPlayerTable(Player)
localfunctionUpdateRig()
for_,vinnext,PlayerTable.Chamdo
fori=1,6do
localQuad=v["Quad"..totring(i)]

ifQuadandQuad.Removethen
Quad:Remove()
end
end
end
ifPlayerTable.RigType=="R15"then
ifnotEnvironment.Viual.Chametting.EntireBodythen
PlayerTable.Cham={
Head={},
UpperToro={},
LeftLowerArm={},LeftUpperArm={},
RightLowerArm={},RightUpperArm={},
LeftLowerLeg={},LeftUpperLeg={},
RightLowerLeg={},RightUpperLeg={}
}
ele
PlayerTable.Cham={
Head={},
UpperToro={},LowerToro={},
LeftLowerArm={},LeftUpperArm={},LeftHand={},
RightLowerArm={},RightUpperArm={},RightHand={},
LeftLowerLeg={},LeftUpperLeg={},LeftFoot={},
RightLowerLeg={},RightUpperLeg={},RightFoot={}
}
end
eleifPlayerTable.RigType=="R6"then
PlayerTable.Cham={
Head={},
Toro={},
["LeftArm"]={},
["RightArm"]={},
["LeftLeg"]={},
["RightLeg"]={}
}
end
for_,vinnext,PlayerTable.Chamdo
fori=1,6do
v["Quad"..totring(i)]=Drawingnew("Quad")
end
end
end
localOldEntireBody=Environment.Viual.Chametting.EntireBody
UpdateRig();PlayerTable.Connection.Cham=Runervice.Rendertepped:Connect(function()
fori,vinnext,PlayerTable.Chamdo
UpdateCham(Player.Character:WaitForChild(i,1/0),v)
end
ifEnvironment.Viual.Chametting.Enabledthen
ifEnvironment.Viual.Chametting.EntireBody~=OldEntireBodythen
UpdateRig();OldEntireBody=Environment.Viual.Chametting.EntireBody
end
end
end)
end,
AddEP=function(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.EP=Drawingnew("Text")
PlayerTable.Connection.EP=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")andPlayer.Character:FindFirtChild("HumanoidRootPart")andPlayer.Character:FindFirtChild("Head")andEnvironment.etting.Enabledthen
localVector,Oncreen=WorldToViewportPoint(Player.Character.Head.Poition)
PlayerTable.EP.Viible=Environment.Viual.EPetting.Enabled
ifOncreenandEnvironment.Viual.EPetting.Enabledthen
PlayerTable.EP.Viible=PlayerTable.Check.AliveandPlayerTable.Check.Teamandtrueorfale
ifPlayerTable.EP.Viiblethen
PlayerTable.EP.Center=true
PlayerTable.EP.ize=Environment.Viual.EPetting.Textize
PlayerTable.EP.Outline=Environment.Viual.EPetting.Outline
PlayerTable.EP.OutlineColor=Environment.Viual.EPetting.OutlineColor
PlayerTable.EP.Color=Environment.Viual.EPetting.TextColor
PlayerTable.EP.Tranparency=Environment.Viual.EPetting.TextTranparency
PlayerTable.EP.Font=Environment.Viual.EPetting.TextFont
localPart,Content,Tool={
Health="("..totring(mathfloor(Player.Character.Humanoid.Health))..")",
Ditance="["..totring(mathfloor((Player.Character.HumanoidRootPart.PoitionorVector3zero-(LocalPlayer.Character.HumanoidRootPart.PoitionorVector3zero)).Magnitude)).."]",
Name=Player.DiplayName==Player.NameandPlayer.NameorPlayer.DiplayName.."{"..Player.Name.."}"
},"",Player.Character:FindFirtChildOfCla("Tool")
ifEnvironment.Viual.EPetting.DiplayNamethen
Content=Part.Name..Content
end
ifEnvironment.Viual.EPetting.DiplayHealththen
Content=Part.Health..(Environment.Viual.EPetting.DiplayNameand""or"")..Content
end
ifEnvironment.Viual.EPetting.DiplayDitancethen
Content=Content..""..Part.Ditance
end
PlayerTable.EP.Text=(Tooland"["..Tool.Name.."]\n"or"")..Content
PlayerTable.EP.Poition=Vector2new(Vector.X,Vector.Y-Environment.Viual.EPetting.Offet-(Tooland10or0))
end
ele
PlayerTable.EP.Viible=fale
end
ele
PlayerTable.EP.Viible=fale
end
end)
end,
AddTracer=function(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.Tracer=Drawingnew("Line")
PlayerTable.Connection.Tracer=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")andPlayer.Character:FindFirtChild("HumanoidRootPart")andPlayer.Character:FindFirtChild("Head")andEnvironment.etting.Enabledthen
localHRPCFrame,HRPize=Player.Character.HumanoidRootPart.CFrame,Player.Character.HumanoidRootPart.ize
local_3DVector,Oncreen=WorldToViewportPoint(HRPCFrame*CFramenew(0,-HRPize.Y-0.5,0).Poition)
local_2DVector=WorldToViewportPoint(Player.Character.HumanoidRootPart.Poition)
localHeadOffet=WorldToViewportPoint(Player.Character.Head.Poition+Vector3new(0,0.5,0))
localLegOffet=WorldToViewportPoint(Player.Character.HumanoidRootPart.Poition-Vector3new(0,1.5,0))
ifOncreenandEnvironment.Viual.Traceretting.Enabledthen
ifEnvironment.Viual.Traceretting.Enabledthen
PlayerTable.Tracer.Viible=PlayerTable.Check.AliveandPlayerTable.Check.Teamandtrueorfale
ifPlayerTable.Tracer.Viiblethen
PlayerTable.Tracer.Thickne=Environment.Viual.Traceretting.Thickne
PlayerTable.Tracer.Color=Environment.Viual.Traceretting.Color
PlayerTable.Tracer.Tranparency=Environment.Viual.Traceretting.Tranparency
PlayerTable.Tracer.To=Environment.Viual.Boxetting.Type==1andVector2new(_3DVector.X,_3DVector.Y)orVector2new(_2DVector.X,_2DVector.Y-(HeadOffet.Y-LegOffet.Y)*0.75)
ifEnvironment.Viual.Traceretting.Type==1then
PlayerTable.Tracer.From=Vector2new(Camera.Viewportize.X/2,Camera.Viewportize.Y)
eleifEnvironment.Viual.Traceretting.Type==2then
PlayerTable.Tracer.From=Vector2new(Camera.Viewportize.X/2,Camera.Viewportize.Y/2)
eleifEnvironment.Viual.Traceretting.Type==3then
PlayerTable.Tracer.From=Vector2new(UerInputervice:GetMoueLocation().X,UerInputervice:GetMoueLocation().Y)
ele
PlayerTable.Tracer.From=Vector2new(Camera.Viewportize.X/2,Camera.Viewportize.Y)
end
end
end
ele
PlayerTable.Tracer.Viible=fale
end
ele
PlayerTable.Tracer.Viible=fale
end
end)
end,
AddBox=function(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.Box.quare=Drawingnew("quare")
PlayerTable.Box.TopLeftLine=Drawingnew("Line")
PlayerTable.Box.TopLeftLine=Drawingnew("Line")
PlayerTable.Box.TopRightLine=Drawingnew("Line")
PlayerTable.Box.BottomLeftLine=Drawingnew("Line")
PlayerTable.Box.BottomRightLine=Drawingnew("Line")
localfunctionViibility(Bool)
ifEnvironment.Viual.Boxetting.Type==1then
PlayerTable.Box.quare.Viible=notBool
PlayerTable.Box.TopLeftLine.Viible=Bool
PlayerTable.Box.TopRightLine.Viible=Bool
PlayerTable.Box.BottomLeftLine.Viible=Bool
PlayerTable.Box.BottomRightLine.Viible=Bool
eleifEnvironment.Viual.Boxetting.Type==2then
PlayerTable.Box.quare.Viible=Bool
PlayerTable.Box.TopLeftLine.Viible=notBool
PlayerTable.Box.TopRightLine.Viible=notBool
PlayerTable.Box.BottomLeftLine.Viible=notBool
PlayerTable.Box.BottomRightLine.Viible=notBool
end
end
localfunctionViibility2(Bool)
PlayerTable.Box.quare.Viible=Bool
PlayerTable.Box.TopLeftLine.Viible=Bool
PlayerTable.Box.TopRightLine.Viible=Bool
PlayerTable.Box.BottomLeftLine.Viible=Bool
PlayerTable.Box.BottomRightLine.Viible=Bool
end
PlayerTable.Connection.Box=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")andPlayer.Character:FindFirtChild("HumanoidRootPart")andPlayer.Character:FindFirtChild("Head")andEnvironment.etting.Enabledthen
localVector,Oncreen=WorldToViewportPoint(Player.Character.HumanoidRootPart.Poition)
Viibility(Environment.Viual.Boxetting.Enabled)
ifOncreenandEnvironment.Viual.Boxetting.Enabledthen
ifPlayerTable.Check.AliveandPlayerTable.Check.Teamthen
Viibility(true)
ele
Viibility2(fale)
end
localHRPCFrame,HRPize=Player.Character.HumanoidRootPart.CFrame,Player.Character.HumanoidRootPart.ize*Environment.Viual.Boxetting.Increae
localHeadOffet=WorldToViewportPoint(Player.Character.Head.Poition+Vector3new(0,0.5,0))
localLegOffet=WorldToViewportPoint(Player.Character.HumanoidRootPart.Poition-Vector3new(0,3,0))
localTopLeftPoition=WorldToViewportPoint(HRPCFrame*CFramenew(HRPize.X,HRPize.Y,0).Poition)
localTopRightPoition=WorldToViewportPoint(HRPCFrame*CFramenew(-HRPize.X,HRPize.Y,0).Poition)
localBottomLeftPoition=WorldToViewportPoint(HRPCFrame*CFramenew(HRPize.X,-HRPize.Y-0.5,0).Poition)
localBottomRightPoition=WorldToViewportPoint(HRPCFrame*CFramenew(-HRPize.X,-HRPize.Y-0.5,0).Poition)
ifPlayerTable.Box.quare.ViibleandnotPlayerTable.Box.TopLeftLine.ViibleandnotPlayerTable.Box.TopRightLine.ViibleandnotPlayerTable.Box.BottomLeftLine.ViibleandnotPlayerTable.Box.BottomRightLine.Viiblethen
PlayerTable.Box.quare.Thickne=Environment.Viual.Boxetting.Thickne
PlayerTable.Box.quare.Color=Environment.Viual.Boxetting.Color
PlayerTable.Box.quare.Tranparency=Environment.Viual.Boxetting.Tranparency
PlayerTable.Box.quare.Filled=Environment.Viual.Boxetting.Filled
PlayerTable.Box.quare.ize=Vector2new(2000/Vector.Z,HeadOffet.Y-LegOffet.Y)
PlayerTable.Box.quare.Poition=Vector2new(Vector.X-PlayerTable.Box.quare.ize.X/2,Vector.Y-PlayerTable.Box.quare.ize.Y/2)
eleifnotPlayerTable.Box.quare.ViibleandPlayerTable.Box.TopLeftLine.ViibleandPlayerTable.Box.TopRightLine.ViibleandPlayerTable.Box.BottomLeftLine.ViibleandPlayerTable.Box.BottomRightLine.Viiblethen
PlayerTable.Box.TopLeftLine.Thickne=Environment.Viual.Boxetting.Thickne
PlayerTable.Box.TopLeftLine.Tranparency=Environment.Viual.Boxetting.Tranparency
PlayerTable.Box.TopLeftLine.Color=Environment.Viual.Boxetting.Color
PlayerTable.Box.TopRightLine.Thickne=Environment.Viual.Boxetting.Thickne
PlayerTable.Box.TopRightLine.Tranparency=Environment.Viual.Boxetting.Tranparency
PlayerTable.Box.TopRightLine.Color=Environment.Viual.Boxetting.Color
PlayerTable.Box.BottomLeftLine.Thickne=Environment.Viual.Boxetting.Thickne
PlayerTable.Box.BottomLeftLine.Tranparency=Environment.Viual.Boxetting.Tranparency
PlayerTable.Box.BottomLeftLine.Color=Environment.Viual.Boxetting.Color
PlayerTable.Box.BottomRightLine.Thickne=Environment.Viual.Boxetting.Thickne
PlayerTable.Box.BottomRightLine.Tranparency=Environment.Viual.Boxetting.Tranparency
PlayerTable.Box.BottomRightLine.Color=Environment.Viual.Boxetting.Color
PlayerTable.Box.TopLeftLine.From=Vector2new(TopLeftPoition.X,TopLeftPoition.Y)
PlayerTable.Box.TopLeftLine.To=Vector2new(TopRightPoition.X,TopRightPoition.Y)
PlayerTable.Box.TopRightLine.From=Vector2new(TopRightPoition.X,TopRightPoition.Y)
PlayerTable.Box.TopRightLine.To=Vector2new(BottomRightPoition.X,BottomRightPoition.Y)
PlayerTable.Box.BottomLeftLine.From=Vector2new(BottomLeftPoition.X,BottomLeftPoition.Y)
PlayerTable.Box.BottomLeftLine.To=Vector2new(TopLeftPoition.X,TopLeftPoition.Y)
PlayerTable.Box.BottomRightLine.From=Vector2new(BottomRightPoition.X,BottomRightPoition.Y)
PlayerTable.Box.BottomRightLine.To=Vector2new(BottomLeftPoition.X,BottomLeftPoition.Y)
end
ele
Viibility2(fale)
end
ele
Viibility2(fale)
end
end)
end,

AddHeadDot=function(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.HeadDot=Drawingnew("Circle")
PlayerTable.Connection.HeadDot=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")andPlayer.Character:FindFirtChild("Head")andEnvironment.etting.Enabledthen
localVector,Oncreen=WorldToViewportPoint(Player.Character.Head.Poition)
PlayerTable.HeadDot.Viible=Environment.Viual.HeadDotetting.Enabled
ifOncreenandEnvironment.Viual.HeadDotetting.Enabledthen
ifEnvironment.Viual.HeadDotetting.Enabledthen
PlayerTable.HeadDot.Viible=PlayerTable.Check.AliveandPlayerTable.Check.Teamandtrueorfale
ifPlayerTable.HeadDot.Viiblethen
PlayerTable.HeadDot.Thickne=Environment.Viual.HeadDotetting.Thickne
PlayerTable.HeadDot.Color=Environment.Viual.HeadDotetting.Color
PlayerTable.HeadDot.Tranparency=Environment.Viual.HeadDotetting.Tranparency
PlayerTable.HeadDot.Numide=Environment.Viual.HeadDotetting.ide
PlayerTable.HeadDot.Filled=Environment.Viual.HeadDotetting.Filled
PlayerTable.HeadDot.Poition=Vector2new(Vector.X,Vector.Y)
localTop,Bottom=WorldToViewportPoint((Player.Character.Head.CFrame*CFramenew(0,Player.Character.Head.ize.Y/2,0)).Poition),WorldToViewportPoint((Player.Character.Head.CFrame*CFramenew(0,-Player.Character.Head.ize.Y/2,0)).Poition)
PlayerTable.HeadDot.Radiu=mathab((Top-Bottom).Y)-3
end
end
ele
PlayerTable.HeadDot.Viible=fale
end
ele
PlayerTable.HeadDot.Viible=fale
end
end)
end,

AddHealthBar=function(Player)
localPlayerTable=GetPlayerTable(Player)
PlayerTable.HealthBar.Main=Drawingnew("quare")
PlayerTable.HealthBar.Outline=Drawingnew("quare")
PlayerTable.Connection.HealthBar=Runervice.Rendertepped:Connect(function()
ifPlayer.CharacterandPlayer.Character:FindFirtChildOfCla("Humanoid")andPlayer.Character:FindFirtChild("HumanoidRootPart")andEnvironment.etting.Enabledthen
localVector,Oncreen=WorldToViewportPoint(Player.Character.HumanoidRootPart.Poition)
localLeftPoition=WorldToViewportPoint(Player.Character.HumanoidRootPart.CFrame*CFramenew(Player.Character.HumanoidRootPart.ize.X,Player.Character.HumanoidRootPart.ize.Y/2,0).Poition)
localRightPoition=WorldToViewportPoint(Player.Character.HumanoidRootPart.CFrame*CFramenew(-Player.Character.HumanoidRootPart.ize.X,Player.Character.HumanoidRootPart.ize.Y/2,0).Poition)
PlayerTable.HealthBar.Main.Viible=Environment.Viual.HealthBaretting.Enabled
PlayerTable.HealthBar.Outline.Viible=Environment.Viual.HealthBaretting.Enabled
ifOncreenandEnvironment.Viual.HealthBaretting.Enabledthen
ifEnvironment.Viual.HealthBaretting.Enabledthen
localHumanoid=Player.Character:FindFirtChildOfCla("Humanoid")
PlayerTable.HealthBar.Main.Viible=PlayerTable.Check.AliveandPlayerTable.Check.Teamandtrueorfale
PlayerTable.HealthBar.Outline.Viible=PlayerTable.HealthBar.Main.Viible
ifPlayerTable.HealthBar.Main.Viiblethen
PlayerTable.HealthBar.Main.Thickne=1
PlayerTable.HealthBar.Main.Color=Color3fromRGB(255-mathfloor(Humanoid.Health/100*255),mathfloor(Humanoid.Health/100*255),Environment.Viual.HealthBaretting.Blue)
PlayerTable.HealthBar.Main.Tranparency=Environment.Viual.HealthBaretting.Tranparency
PlayerTable.HealthBar.Main.Filled=true
PlayerTable.HealthBar.Main.ZIndex=2
PlayerTable.HealthBar.Outline.Thickne=3
PlayerTable.HealthBar.Outline.Color=Environment.Viual.HealthBaretting.OutlineColor
PlayerTable.HealthBar.Outline.Tranparency=Environment.Viual.HealthBaretting.Tranparency
PlayerTable.HealthBar.Outline.Filled=fale
PlayerTable.HealthBar.Main.ZIndex=1
ifEnvironment.Viual.HealthBaretting.Type==1then
PlayerTable.HealthBar.Outline.ize=Vector2new(2000/Vector.Z,Environment.Viual.HealthBaretting.ize)
PlayerTable.HealthBar.Main.ize=Vector2new(PlayerTable.HealthBar.Outline.ize.X*(Humanoid.Health/100),PlayerTable.HealthBar.Outline.ize.Y)
PlayerTable.HealthBar.Main.Poition=Vector2new(Vector.X-PlayerTable.HealthBar.Outline.ize.X/2,Vector.Y-PlayerTable.HealthBar.Outline.ize.X/2-Environment.Viual.HealthBaretting.Offet)
eleifEnvironment.Viual.HealthBaretting.Type==2then
PlayerTable.HealthBar.Outline.ize=Vector2new(2000/Vector.Z,Environment.Viual.HealthBaretting.ize)
PlayerTable.HealthBar.Main.ize=Vector2new(PlayerTable.HealthBar.Outline.ize.X*(Humanoid.Health/100),PlayerTable.HealthBar.Outline.ize.Y)
PlayerTable.HealthBar.Main.Poition=Vector2new(Vector.X-PlayerTable.HealthBar.Outline.ize.X/2,Vector.Y+PlayerTable.HealthBar.Outline.ize.X/2+Environment.Viual.HealthBaretting.Offet)
eleifEnvironment.Viual.HealthBaretting.Type==3then
PlayerTable.HealthBar.Outline.ize=Vector2new(Environment.Viual.HealthBaretting.ize,2500/Vector.Z)
PlayerTable.HealthBar.Main.ize=Vector2new(PlayerTable.HealthBar.Outline.ize.X,PlayerTable.HealthBar.Outline.ize.Y*(Humanoid.Health/100))
PlayerTable.HealthBar.Main.Poition=Vector2new(LeftPoition.X-Environment.Viual.HealthBaretting.Offet,Vector.Y-PlayerTable.HealthBar.Outline.ize.Y/2)
eleifEnvironment.Viual.HealthBaretting.Type==4then
PlayerTable.HealthBar.Outline.ize=Vector2new(Environment.Viual.HealthBaretting.ize,2500/Vector.Z)
PlayerTable.HealthBar.Main.ize=Vector2new(PlayerTable.HealthBar.Outline.ize.X,PlayerTable.HealthBar.Outline.ize.Y*(Humanoid.Health/100))
PlayerTable.HealthBar.Main.Poition=Vector2new(RightPoition.X+Environment.Viual.HealthBaretting.Offet,Vector.Y-PlayerTable.HealthBar.Outline.ize.Y/2)
end
PlayerTable.HealthBar.Outline.Poition=PlayerTable.HealthBar.Main.Poition
end
end
ele
PlayerTable.HealthBar.Main.Viible=fale
PlayerTable.HealthBar.Outline.Viible=fale
end
ele
PlayerTable.HealthBar.Main.Viible=fale
PlayerTable.HealthBar.Outline.Viible=fale
end
end)
end,
AddCrohair=function()
localAxiX,AxiY=Camera.Viewportize.X/2,Camera.Viewportize.Y/2
erviceConnection.AxiConnection=Runervice.Rendertepped:Connect(function()
ifEnvironment.Crohair.etting.Enabledthen
ifEnvironment.Crohair.etting.Type==1then
AxiX,AxiY=UerInputervice:GetMoueLocation().X,UerInputervice:GetMoueLocation().Y
eleifEnvironment.Crohair.etting.Type==2then
AxiX,AxiY=Camera.Viewportize.X/2,Camera.Viewportize.Y/2
ele
Environment.Crohair.etting.Type=1
end
end
end)
erviceConnection.CrohairConnection=Runervice.Rendertepped:Connect(function()
ifEnvironment.Crohair.etting.Enabledthen
Environment.Crohair.Part.LeftLine.Viible=Environment.Crohair.etting.Enabled
Environment.Crohair.Part.LeftLine.Color=Environment.Crohair.etting.Color
Environment.Crohair.Part.LeftLine.Thickne=Environment.Crohair.etting.Thickne
Environment.Crohair.Part.LeftLine.Tranparency=Environment.Crohair.etting.Tranparency
Environment.Crohair.Part.LeftLine.From=Vector2new(AxiX-(mathco(mathrad(Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize),AxiY-(mathin(mathrad(Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize))
Environment.Crohair.Part.LeftLine.To=Vector2new(AxiX-(mathco(mathrad(Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)),AxiY-(mathin(mathrad(Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)))
Environment.Crohair.Part.RightLine.Viible=Environment.Crohair.etting.Enabled
Environment.Crohair.Part.RightLine.Color=Environment.Crohair.etting.Color
Environment.Crohair.Part.RightLine.Thickne=Environment.Crohair.etting.Thickne
Environment.Crohair.Part.RightLine.Tranparency=Environment.Crohair.etting.Tranparency
Environment.Crohair.Part.RightLine.From=Vector2new(AxiX+(mathco(mathrad(Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize),AxiY+(mathin(mathrad(Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize))
Environment.Crohair.Part.RightLine.To=Vector2new(AxiX+(mathco(mathrad(Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)),AxiY+(mathin(mathrad(Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)))
Environment.Crohair.Part.TopLine.Viible=Environment.Crohair.etting.Enabled
Environment.Crohair.Part.TopLine.Color=Environment.Crohair.etting.Color
Environment.Crohair.Part.TopLine.Thickne=Environment.Crohair.etting.Thickne
Environment.Crohair.Part.TopLine.Tranparency=Environment.Crohair.etting.Tranparency
Environment.Crohair.Part.TopLine.From=Vector2new(AxiX-(mathin(mathrad(-Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize),AxiY-(mathco(mathrad(-Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize))
Environment.Crohair.Part.TopLine.To=Vector2new(AxiX-(mathin(mathrad(-Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)),AxiY-(mathco(mathrad(-Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)))
Environment.Crohair.Part.BottomLine.Viible=Environment.Crohair.etting.Enabled
Environment.Crohair.Part.BottomLine.Color=Environment.Crohair.etting.Color
Environment.Crohair.Part.BottomLine.Thickne=Environment.Crohair.etting.Thickne
Environment.Crohair.Part.BottomLine.Tranparency=Environment.Crohair.etting.Tranparency
Environment.Crohair.Part.BottomLine.From=Vector2new(AxiX+(mathin(mathrad(-Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize),AxiY+(mathco(mathrad(-Environment.Crohair.etting.Rotation))*Environment.Crohair.etting.Gapize))
Environment.Crohair.Part.BottomLine.To=Vector2new(AxiX+(mathin(mathrad(-Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)),AxiY+(mathco(mathrad(-Environment.Crohair.etting.Rotation))*(Environment.Crohair.etting.ize+Environment.Crohair.etting.Gapize)))
Environment.Crohair.Part.CenterDot.Viible=Environment.Crohair.etting.EnabledandEnvironment.Crohair.etting.CenterDot
Environment.Crohair.Part.CenterDot.Color=Environment.Crohair.etting.CenterDotColor
Environment.Crohair.Part.CenterDot.Radiu=Environment.Crohair.etting.CenterDotize
Environment.Crohair.Part.CenterDot.Tranparency=Environment.Crohair.etting.CenterDotTranparency
Environment.Crohair.Part.CenterDot.Filled=Environment.Crohair.etting.CenterDotFilled
Environment.Crohair.Part.CenterDot.Thickne=Environment.Crohair.etting.CenterDotThickne
Environment.Crohair.Part.CenterDot.Poition=Vector2new(AxiX,AxiY)
ele
Environment.Crohair.Part.LeftLine.Viible=fale
Environment.Crohair.Part.RightLine.Viible=fale
Environment.Crohair.Part.TopLine.Viible=fale
Environment.Crohair.Part.BottomLine.Viible=fale
Environment.Crohair.Part.CenterDot.Viible=fale
end
end)
end
}
localfunctionWrap(Player)
ifnotGetPlayerTable(Player)then
localTable,Value=nil,{Name=Player.Name,Check={Alive=true,Team=true},Connection={},EP=nil,Tracer=nil,HeadDot=nil,HealthBar={Main=nil,Outline=nil},Box={quare=nil,TopLeftLine=nil,TopRightLine=nil,BottomLeftLine=nil,BottomRightLine=nil},Cham={}}
for_,vinnext,Environment.WrappedPlayerdo
ifv[1]==Player.Namethen
Table=v
end
end
ifnotTablethen
Environment.WrappedPlayer[#Environment.WrappedPlayer+1]=Value
AignRigType(Player)
InitCheck(Player)
Viual.AddCham(Player)
Viual.AddEP(Player)
Viual.AddTracer(Player)
Viual.AddBox(Player)
Viual.AddHeadDot(Player)
Viual.AddHealthBar(Player)
end
end
end
localfunctionUnWrap(Player)
localTable,Index=nil,nil
fori,vinnext,Environment.WrappedPlayerdo
ifv.Name==Player.Namethen
Table,Index=v,i
end
end
ifTablethen
for_,vinnext,Table.Connectiondo
v:Diconnect()
end
pcall(function()
Table.EP:Remove()
Table.Tracer:Remove()
Table.HeadDot:Remove()
Table.HealthBar.Main:Remove()
Table.HealthBar.Outline:Remove()
end)
for_,vinnext,Table.Boxdo
ifnotv.Removethen
continue
ele
v:Remove()
end
end
for_,vinnext,Table.Chamdo
for_,v2innext,vdo
ifnotv2.Removethen
continue
ele
v2:Remove()
end
end
end
Environment.WrappedPlayer[Index]=nil
end
end
localfunctionLoad()
Viual.AddCrohair()
erviceConnection.PlayerAddedConnection=Player.PlayerAdded:Connect(Wrap)
erviceConnection.PlayerRemovingConnection=Player.PlayerRemoving:Connect(UnWrap)
erviceConnection.ReWrapPlayer=Runervice.Rendertepped:Connect(function()
for_,vinnext,Player:GetPlayer()do
ifv~=LocalPlayerthen
Wrap(v)
end
end
wait(30)
end)
end
Environment.Function={}
functionEnvironment.Function:Exit()
for_,vinnext,erviceConnectiondo
v:Diconnect()
end
for_,vinnext,Environment.Crohair.Partdo
v:Remove()
end
for_,vinnext,Player:GetPlayer()do
ifv~=LocalPlayerthen
UnWrap(v)
end
end
getgenv().natxyzEP.WallHack.Function=nil
getgenv().natxyzEP.WallHack=nil
Load=nil;GetPlayerTable=nil;AignRigType=nil;InitCheck=nil;UpdateCham=nil;Viual=nil;Wrap=nil;UnWrap=nil
end
functionEnvironment.Function:Retart()
for_,vinnext,Player:GetPlayer()do
ifv~=LocalPlayerthen
UnWrap(v)
end
end
for_,vinnext,erviceConnectiondo
v:Diconnect()
end
Load()
end
etmetatable(Environment.Function,{
__newindex=warn
})
